### ISSUE TITLE
Importing works but put everything in compendiums

### ISSUE THREAD

**Issue by vonv** [spetzel2020/easy-exports#12]

**Comment by spetzel2020** [comment]
This is by design. If you would like different behavior, can you clarify
what that would be?

**Comment by vonv** [comment]
Sorry. I was remembering that when i exported a journal, it imported it in the journal entries not in the compendiums. My mistake.
Sorry and thanks for the last fix and your work.

**Comment by spetzel2020** [comment]
No problem; thanks for the quick response!
