### ISSUE TITLE
Any plans to support Foundry v10?

### ISSUE THREAD

**Issue by steveculshaw** [spetzel2020/easy-exports#15]
Any plans to support Foundry v10?

Cheers,
SteveC.

**Comment by spetzel2020** [comment]
Yes; I was blind-sided by the fact that it worked in an earlier v10 build.
Should be able to look at it next week.

**Comment by steveculshaw** [comment]
Much appreciated !

**Comment by spetzel2020** [comment]
Released v0.7.0 ; only change was to fix a spurious `.css` file not present warning from Foundry v10. I lightly tested the Exports, Imports, and Full Backup - please open an issue if anything else isn't working.

**Comment by steveculshaw** [comment]
@spetzel2020 Many thanks
