### ISSUE TITLE
Unable to download latest version

### ISSUE THREAD

**Issue by JamzTheMan** [spetzel2020/easy-exports#9]

**Comment by JamzTheMan** [comment]
There is an error in your module.json

https://github.com/spetzel2020/easy-exports/releases/download/v0.6.2/easy-exports.zip
vs
https://github.com/spetzel2020/easy-exports/releases/download/0.6.2/easy-exports.zip

**Comment by spetzel2020** [comment]
Embarrassing - thanks for bugging!

**Comment by spetzel2020** [comment]
Fixed now and replaced v0.6.2. Sorry about that.
